services:
  server:
    container_name: tender_app
    build:
      context: ../
      dockerfile: docker/DockerfileApp
      target: final
    env_file:
      - ../.env
    ports:
      - "8080:8080"
